### ISSUE TITLE
Pands Project planning Phase 1

### ISSUE THREAD

**Issue by Ainara12** [Ainara12/Pands-project#1]
### Phase one: Investigate data set origins and look at approaches made by others. 

- [x] Document origin of data set in README.md
- [x] Download data set and add it to this repository
- [x] Explained data set variables 
- [x] Looked at other people approaches to analyse data and decide which tools I will use to complete this project
